### ISSUE TITLE
Small typo to fix

### ISSUE THREAD

**Issue by catprisbrey** [mohsenph69/godot-ambientcg#1]
When the plugin is enabled and in the top toolbar, the new tab is spelled "abmient" and not "ambient". 

Wonderful plugin. This sort of integration into godot is genius and exactly what the software needed to speedup workflow! i love it.

**Comment by mohsenph69** [comment]
Thanks for your contribution
Done!!!

**Comment by catprisbrey** [comment]
Thanks, love this plugin.
